### PR TITLE
Fix watcher ORM ban on Airflow 3.0 by detecting the supervisor at runtime

### PR DESCRIPTION
**Pull request by pankajastro**
## Problem

In `WATCHER` mode on **Airflow 3.0**, the deferred triggerer's `get_xcom_val_af3` → `XCom.get_one` raises:

```
File "cosmos/operators/_watcher/triggerer.py", line 82, in get_xcom_val_af3
    return await sync_to_async(XCom.get_one)(...)
File "airflow/sdk/bases/xcom.py", line 242, in get_one
    from airflow.sdk.execution_time.task_runner import SUPERVISOR_COMMS
ImportError: cannot import name 'SUPERVISOR_COMMS' from 'airflow.sdk.execution_time.task_runner'
```

This was first hit under `dag.test()` (#2693). A prior revision worked around it by gating the task-SDK path at `>= 3.1` and routing **all** of AF 3.0 to the direct-DB ORM — which then crashed real 3.0 workers and triggerers with `RuntimeError: Direct database access via the ORM is not allowed in Airflow 3.0` (seen on `3.0.0+astro.2`).

## Root cause

The version gate rested on the premise that "a triggerer never binds `SUPERVISOR_COMMS` on 3.0." Inspecting the installed AF 3.0 source shows that premise is wrong:

- The worker (`task_runner.main()`) and the triggerer (`TriggererJobRunner.init_comms()`) **both bind `SUPERVISOR_COMMS` at runtime**, so the task-SDK APIs (`XCom.get_one`, `RuntimeTaskInstance.get_task_states`) **work** there — and the supervisor installs `BlockedDBSession`, so **ORM access is banned**.
- `SUPERVISOR_COMMS` is unbound **only** with no supervisor (`dag.test()` inline) — and there `XCom.get_one`/`get_task_states` raise `ImportError`/`NameError` while ORM access **is** permitted.

A single version gate can't tell "under a supervisor" from "not," so it caused the `ImportError` under `dag.test()` and the ORM `RuntimeError` on real workers/triggerers.

## Fix — detect the supervisor at call time

On AF ≥3.0, prefer the task-SDK and fall back to the ORM only when there is no supervisor:

- **`state.py`** `build_producer_state_fetcher` — try `RuntimeTaskInstance.get_task_states`; on `NameError` (no supervisor) → ORM.
- **`triggerer.py`** `get_xcom_val` — try `XCom.get_one`; on `ImportError`/`NameError` → ORM.

| Context | Path |
|---|---|
| Real 3.0 worker / triggerer (SDK ✅, ORM banned) | task-SDK |
| `dag.test()` inline, AF 3.0/3.1 (no supervisor) | ORM fallback |
| Airflow 2.x | ORM |

This targets AF 3.0 (3.1+ is unaffected — the CI skip was 3.0-only). A version gate is insufficient *within* 3.0: the same build runs as a real worker/triggerer (`SUPERVISOR_COMMS` bound → task-SDK works, ORM banned) and as `dag.test()` inline (no supervisor → task-SDK raises, ORM permitted), so the choice must be made at runtime, not by version.

## Testing

- **Worker/triggerer (task-SDK) path:** verified by source inspection (above) + unit tests — AF3 producer-state tests run at **3.0.0**; `test_get_xcom_val_branches` expects the task-SDK path on 3.0.
- **No-supervisor (ORM) path:** new `..._falls_back_to_orm_without_supervisor` (state) and parametrized `ImportError`/`NameError` fallback (triggerer) tests; the re-enabled `watcher_with_freshness_check.py` `dag.test()` integration cell.
- ✅ Full unit suite green on the AF 3.0 hatch env; ✅ mypy clean. AF 2.x ORM tests pass.

Refs: #2693, apache/airflow#51816, apache/airflow#59093

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

File: cosmos/operators/_watcher/triggerer.py [hunk 1]
```diff
@@ -117,10 +116,12 @@ async def get_xcom_val(self, key: str) -> Any | None:
...
         )
-        if AIRFLOW_VERSION < Version("3.0.0"):
-            return await self.get_xcom_val_af2(key)
-        else:
+        # Airflow 3.0's task-SDK XCom API raises outside a supervisor (e.g. dag.test()), so only
+        # use it on 3.1+; Airflow < 3.1 reads XCom directly from the metadata DB. See #51816.
+        if airflow_supports_task_sdk_runtime(AIRFLOW_VERSION):
             return await self.get_xcom_val_af3(key)
+        else:
+            return await self.get_xcom_val_af2(key)
```
[the remark this answers is not in the document]
Comment (pankajastro) [reply cosmos/operators/_watcher/triggerer.py]: Thanks — this was a deliberate change, and the PR description has been updated (it previously described the older try/except approach, which is what this comment is reacting to).

We initially used the `try/except ImportError` fallback precisely to "keep the SDK primary on AF 3.0." The CI run on this branch disproved that premise: the task-SDK runtime APIs fail at *every* call site on AF 3.0 in the triggerer — the integration log showed `RuntimeTaskInstance.get_task_states` raising `NameError: name 'SUPERVISOR_COMMS' is not defined` on every poll, not just `XCom.get_one`. A triggerer is not a task runner, so it never initializes `SUPERVISOR_COMMS`; the SDK path is not actually usable on AF 3.0 here even outside `dag.test()`, and there are no production AF 3.0 watcher reports to suggest otherwise.

So routing all of AF 3.0 to the direct-DB ORM path isn't a regression — it's the path that actually works in a triggerer on 3.0 (it's metadata-DB-connected), and it's the approach Airflow maintainers recommend for non-runner contexts (apache/airflow#51816, #59093). The version gate is deterministic, consistent across both call sites, and avoids per-poll failed-SDK-call + warning-log spam.

File: tests/operators/_watcher/test_triggerer.py [hunk 2]
```diff
@@ -133,8 +133,8 @@ async def test_parse_dbt_node_status_for_test_sensor(self):
     @pytest.mark.parametrize(
         "airflow_version, expected_val",
         [
-            (Version("2.11.0"), "af2"),  # Airflow < 3 uses get_xcom_val_af2
-            (Version("3.0.0"), "af3"),  # Airflow >= 3 uses get_xcom_val_af3
+            (Version("2.11.0"), "af2"),  # Airflow < 3.1 uses the direct-DB get_xcom_val_af2
+            (Version("3.1.0"), "af3"),  # Airflow >= 3.1 uses the task-SDK get_xcom_val_af3
         ],
```
[the remark this answers is not in the document]
Comment (pankajastro) [reply tests/operators/_watcher/test_triggerer.py:142]: Good call — added an explicit `(Version("3.0.0"), "af2")` row to the branch-selection test in e7f5262, so it now documents the AF 3.0 regression boundary (3.0 routes to the direct-DB `get_xcom_val_af2`).

File: cosmos/operators/_watcher/triggerer.py (hunk 1 above)
[the remark this answers is not in the document]
Comment (pankajastro) [reply cosmos/operators/_watcher/triggerer.py]: This was on an earlier `>= 3.1` revision. The current code already does exactly this: the gate is `AIRFLOW_VERSION < Version("3.0.0")` for the ORM path, and on Airflow >= 3.0 `get_xcom_val` attempts `get_xcom_val_af3` first and only falls back to `get_xcom_val_af2` on `(ImportError, NameError)` (no supervisor). So the task-SDK path is primary on a real 3.0 worker/triggerer.

File: tests/operators/_watcher/test_triggerer.py (hunk 2 above)
[the remark this answers is not in the document]
Comment (pankajastro) [reply tests/operators/_watcher/test_triggerer.py:142]: `test_get_xcom_val_branches` now includes an explicit `(Version("3.0.0"), "af3")` case (alongside `3.1.0`), and `test_get_xcom_val_af3_falls_back_to_orm_without_supervisor` exercises the `ImportError`/`NameError` -> ORM fallback at `3.0.0`. So the 3.0 boundary is covered.

File: cosmos/operators/_watcher/state.py [hunk 3]
```diff
@@ -145,16 +145,32 @@ def build_producer_state_fetcher(
...
+    the correct data source differs between them -- so the choice is made at call time, not
+    by version alone:
+
+    * Inside a task-SDK worker (the sensor's synchronous ``poke()``), direct ORM access is
+      forbidden -- ``create_session`` raises ``RuntimeError: Direct database access via the
+      ORM is not allowed in Airflow 3.0`` -- but ``RuntimeTaskInstance.get_task_states`` works
+      because the worker binds ``SUPERVISOR_COMMS``.
+    * Outside a supervisor (``dag.test()`` running inline, or the Airflow 3.0 triggerer process
+      where ``SUPERVISOR_COMMS`` is never bound), ``get_task_states`` raises ``NameError`` while
+      ORM access *is* permitted.
```
[the remark this answers is not in the document]
Comment (pankajastro) [reply cosmos/operators/_watcher/state.py]: Good catch — fixed in 903c0305. The docstring no longer lists the Airflow 3.0 triggerer as a no-supervisor context; it now states the no-supervisor case is `dag.test()` running inline, and that a real worker and a real triggerer both bind `SUPERVISOR_COMMS` and take the task-SDK path.

File: cosmos/operators/_watcher/state.py [hunk 4]
```diff
@@ -184,9 +207,15 @@ def fetch_state_airflow3() -> str | None:
                 task_ids=[producer_task_id],
                 run_ids=[run_id],
             )
-        except NameError as exc:  # pragma: no cover - Airflow 3.0 missing supervisor comms
-            logger.warning("RuntimeTaskInstance.get_task_states unavailable due to NameError: %s", exc)
-            return None
+        except NameError as exc:
+            # No task-SDK supervisor (e.g. dag.test() inline, or the Airflow 3.0 triggerer):
+            # SUPERVISOR_COMMS is unbound. Read producer state from the metadata DB, which is
+            # permitted in these non-supervisor contexts.
```
[the remark this answers is not in the document]
Comment (pankajastro) [reply cosmos/operators/_watcher/state.py]: Fixed in 903c0305 — the NameError-fallback comment now documents the no-supervisor context as `dag.test()` running inline only (the real triggerer binds SUPERVISOR_COMMS and uses the task-SDK path).

**Review by tatiana — COMMENTED** [review]
Hi @pankajastro, thanks for working on this!

I can see that this PR re-enables example_watcher_with_freshness in the Airflow 3.0 integration suite, which is good validation for the `dag.test()` / no-supervisor path. However, the description also states that the original issue (#2693) was reproduced on a live 3.0.0+astro.2 deployment across both worker and triggerer contexts. For this particular claim, I don’t see corresponding before/after evidence:

- Which specific DAG failed before?
- What command or deployment was rerun after this change to demonstrate success?
Do you have logs or screenshots showing that the DAG now passes post-fix?
- Also, while 3.0.0+astro.2 was tested, more recent Astro runtime versions exist (e.g., [3.0.15](https://www.astronomer.io/docs/runtime/runtime-release-notes#astro-runtime-30-15)). Are you able to confirm whether the issue persists - or is resolved - in those newer versions? This would help clarify whether the fix is robust across the 3.0.x runtime line.

Regarding scope and documentation: As I understand it, on Airflow ≥3.0 the supported production path should be the task-SDK. The ORM fallback is intended only for no-supervisor contexts (like dag.test()) where `XCom.get_one` or `RuntimeTaskInstance.get_task_states raise ImportError/NameError`. Would there be a cleaner way of tackling DAG test-only scenario? While the fallback works today because direct metadata DB access is still allowed in test contexts, this feels like a compatibility workaround for known AF 3.0 behavior rather than a general runtime strategy.

**Comment by pankajastro** [comment]
Thanks @tatiana! I updated the description:
  
  - Dropped the "live deployment" wording. The ORM error is just noted as seen on 3.0.0+astro.2. The worker/triggerer path is verified by reading the Airflow 3.0 code and by unit tests; the dag.test() test covers only the no-supervisor (ORM) case.
  - This is an Airflow 3.0 fix. 3.1+ is fine. A version check does not work because the same 3.0 build runs in two ways: a real worker/triggerer must use the task-SDK (the ORM is blocked there), but dag.test() has no supervisor and must use the ORM. So we pick the path at run time, not by version.

  Airflow has no built-in way to check if a supervisor is running. So we just try the task-SDK first, and use the ORM if that fails. I can move this check into a shared _running_under_supervisor() helper if you prefer.

**Comment by tatiana** [comment]
> Thanks @tatiana! I updated the description:
> 
> * Dropped the "live deployment" wording. The ORM error is just noted as seen on 3.0.0+astro.2. The worker/triggerer path is verified by reading the Airflow 3.0 code and by unit tests; the dag.test() test covers only the no-supervisor (ORM) case.

Does this issue surface on Airflow 3.0 without `dag.test()`? My original understanding is that the issue surfaced outside of it:
```
File "cosmos/operators/_watcher/triggerer.py", line 82, in get_xcom_val_af3
    return await sync_to_async(XCom.get_one)(...)
File "airflow/sdk/bases/xcom.py", line 242, in get_one
    from airflow.sdk.execution_time.task_runner import SUPERVISOR_COMMS
ImportError: cannot import name 'SUPERVISOR_COMMS' from 'airflow.sdk.execution_time.task_runner'
```

I do not believe we should change the Cosmos code to make it more complex just to run the Airflow 3.0 DAG test, given that it works with Airflow 3.1 and 3.2.

**Comment by tatiana** [comment]
@pankajastro and I discussed, and we agree that it does not make sense to make Cosmos more complex to support Airflow 3.0 `dag.test`, given that it works for Airflow 3.1 and 3.2 and that it is a problem on the upstream Airflow.
