### ISSUE TITLE
after merging #233 some dbt tasks are failing

### ISSUE THREAD

**Issue by CorsettiS** [astronomer/astronomer-cosmos#234]
After merging #233 there is a problem in running some dbt tasks that rely on 3rd party packages

<img width="600" alt="Screenshot 2023-04-14 at 19 13 09" src="https://user-images.githubusercontent.com/66136602/232017098-5318a3da-1957-44d1-99f3-adf0de2663dd.png">

```
INFO - Compilation Error
INFO -   dbt found 1 package(s) specified in packages.yml, but only 0 package(s) installed in dbt_packages. Run "dbt deps" to install package dependencies.
```

probably this is because of the new isolated nature of the temp folder. maybe by closing #218 this issue is automatically resolved

**Comment by jlaneve** [comment]
@CorsettiS I think the PR I linked should fix this! I tested it with the cosmos-dev repo, but let me know if you continue to see issues.

**Comment by ashishmgofficial** [comment]
@jlaneve This is not resolved. Im facing this as part of 0.6.1 release as well

**Comment by jlaneve** [comment]
> @jlaneve This is not resolved. Im facing this as part of 0.6.1 release as well

Interesting - I'll look into it some more. To confirm, are you using the `install_deps` flag?

**Comment by ashishmgofficial** [comment]
@jlaneve Apologies, i was not aware of the install_deps. just saw this in another thread. Its working with the option enabled. I think this should be documented properly in the documentation site . Ignore, if already done ( I might have missed )

**Comment by jlaneve** [comment]
No worries - I'm going to deprecate the old operator to make sure this doesn't happen to anyone else 🙂. Thank you for tracking this down!
