### PR TITLE
Add apache-airflow 3.3 to the test matrix

### PR DESCRIPTION
**Pull request by pankajkoti**
## What
Adds Apache Airflow **3.3** to the test matrix (additive). Since 3.3.0 has not GA'd, the
`3.3` cell tracks the latest pre-release and switches to **3.3.0 automatically** once it is
released, with no further code change. No new Python exclusions (3.3 supports 3.10–3.13).

## Touchpoints
- `pyproject.toml`, `.github/workflows/test.yml`, `.github/workflows/test-unprivileged.yml` — matrices
- `scripts/test/pre-install-airflow.sh` — dynamic `3.3` install branch
- `docs/policy/compatibility-policy.rst`, `docs/guides/dbt_setup/execution-modes-local-conflicts.rst`
- `tests/utils.py` + call sites — 3.3 API-change fixes

## Live install until 3.3.0 GA
There is no pinned `requirements-airflow-3.3-dbt-1.11.txt` yet, so the `3.3` branch installs live:
- constraints from the **moving `constraints-3-3` branch** (CI keeps it at the HEAD of the 3.3
  line; it pins the providers/transitive deps but intentionally not `apache-airflow` itself), and
- `apache-airflow>=3.3.0b1,<3.4.0` with `--prerelease=allow`, which resolves to the highest
  available 3.3 version: the latest pre-release today, the GA release once it ships.

It also: installs the **docker** provider (else `tests/operators/test_docker.py` fails collection);
installs `apache-airflow-devel-common` unpinned; and **holds `gcsfs<2026`** — `dbt-bigquery` caps
`google-cloud-storage<3.2`, downgrading gcs to 3.1.1, but gcsfs 2026.x needs `gcs>=3.9` (its
`google.cloud.storage.asyncio` client); gcsfs 2025.x has no such floor.

**Follow-up at GA (BOSS-524):** harvest a green CI `pip freeze` into
`requirements/requirements-airflow-3.3-dbt-1.11.txt`, then replace this branch with the
pinned-file `elif`, matching 3.0–3.2.

## Airflow 3.3 compatibility fixes (test code)
The 3.3 cells surfaced two genuine API changes:
- **`DagBag(include_examples=…)` removed** (AIP-66, apache/airflow#66161) → added a version-gated
  `tests.utils.make_dag_bag` helper and routed all call sites through it.
- **`create_default_connections(session)` is now keyword-only** → call
  `create_default_connections(session=session)` (works on 2.9–3.3).

## CI
`test-unprivileged.yml` (`pull_request`) runs the new unit cell from the branch automatically;
`test.yml` (`pull_request_target`) reads its matrix from `main`, so a **TEMP commit** adds this
branch to `test.yml` `push.branches` to run the integration 3.3 cells pre-merge.

**Pre-merge:** revert the TEMP `test.yml` push-trigger entry.

closes BOSS-480

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by pankajkoti** [comment]
Edit: The blocker is resolved ✅  as mentioned in https://github.com/astronomer/astronomer-cosmos/pull/2831#issuecomment-4770120729

------------------

## ⚠️ Blocker — Airflow 3.3 removed `DagBag(include_examples=...)`

The new `3.3` **integration** cells fail at the *Test* step (install is clean) with:

```
TypeError: DagBag.__init__() got an unexpected keyword argument 'include_examples'
ERROR tests/test_example_dags.py
ERROR tests/test_example_dags_no_connections.py
```

**This is an intentional upstream change, not a packaging issue.** `include_examples` was removed from `airflow.dag_processing.dagbag.DagBag.__init__` between 3.2 and 3.3:

| `DagBag.__init__` | `apache-airflow==3.2.2` | `apache-airflow==3.3.0b1` |
|---|---|---|
| `include_examples` param | present (`bool \| ArgNotSet = NOTSET`) | **removed** |

It's part of the **AIP-66** dag-bundle rework — example DAGs are now discovered as dedicated bundles gated by `[core] load_examples` (release note: *"Provider example DAGs as dedicated bundles"*, apache/airflow#66161), so the per-`DagBag` flag is obsolete.

**Affected (cosmos `tests/` only — not `cosmos/` source):** ~9 `DagBag(..., include_examples=False)` call sites — `tests/test_example_dags.py`, `tests/test_example_dags_no_connections.py`, `tests/test_async_example_dag.py`, `tests/utils.py`, `tests/operators/test_virtualenv.py`, `tests/test_example_k8s_dags.py`, `tests/perf/test_performance.py`.

**Fix direction:** version-gate the kwarg — drop `include_examples` on Airflow ≥ 3.3 (cosmos's `tests/utils.py` already version-shims the *import location*; this extends the same idea to the *kwarg*). Pushing a fix attempt next.

**Comment by pankajkoti** [comment]
**Update — resolved.** The `DagBag.include_examples` removal is fixed via a version-gated `tests.utils.make_dag_bag` helper (PEP 440 gotcha noted: the gate compares the release tuple, since `Version("3.3.0b1") >= Version("3.3")` is False). Two further 3.3-specific issues surfaced behind it and are also fixed:

1. `create_default_connections(session)` is **keyword-only** in 3.3 → now called with `session=session`.
2. gcsfs 2026.x (installed by the constraints) needs `google-cloud-storage>=3.9`, but **`dbt-bigquery` caps `google-cloud-storage<3.2`**, downgrading gcs to 3.1.1 → held `gcsfs<2026` (the 2025.x line cosmos already uses, which has no gcs floor).

The 3.3 unit cells are green, and the integration 3.3 cells went 12/12 on the last functional commit (commits since only touch comments).

**Comment by tatiana** [comment]
@pankajkoti yesterday b2 was released, is it worth updating this branch to confirm tests still pass?
https://pypi.org/project/apache-airflow/3.3.0b2/

**Comment by pankajkoti** [comment]
> @pankajkoti yesterday b2 was released, is it worth updating this branch to confirm tests still pass? https://pypi.org/project/apache-airflow/3.3.0b2/

@tatiana yes, already on it.

File: .github/workflows/test.yml [hunk 1]
```diff
@@ -2,7 +2,11 @@ name: test
 
 on:
   push: # Run on pushes to the default branch
-    branches: [main]
+    # TEMP (revert before merge): bump-apache-airflow-3.3.0b1 is listed so a push
+    # event runs THIS branch's workflow + matrix, exercising the new "3.3" integration
+    # cells. pull_request_target reads the matrix from main (where "3.3" doesn't exist
+    # yet), so without this the 3.3 integration jobs won't run until after merge.
+    branches: [main, bump-apache-airflow-3.3.0b1]
```
Comment (pankajkoti) [inline .github/workflows/test.yml]:
```suggestion
    branches: [main]
```

Before merging.

[the remark this answers is not in the document]
Comment (pankajkoti) [reply .github/workflows/test.yml]: This will be reverted before merging the PR, we have the review comment for the same: https://github.com/astronomer/astronomer-cosmos/pull/2831#discussion_r3481229978

**Review by tatiana — APPROVED** [review]
Thanks a lot, @pankajkoti, I'm really happy to see this upgrade has been smoother than 3.1 and 3.2 🎉

**Comment by pankajkoti** [comment]
> Thanks a lot, @pankajkoti, I'm really happy to see this upgrade has been smoother than 3.1 and 3.2 🎉

Thanks, @tatiana, for the quick review. The CI was green previously. But after applying Copilot's latest suggestion, some of the tests are failing. I will fix them and then merge the PR.

**Comment by pankajkoti** [comment]
The failing tests are now passing: https://github.com/astronomer/astronomer-cosmos/actions/runs/28239782202/job/83664393650?pr=2831

Going ahead with merging the PR now, so we get to test the RC1 install happens automatically when it comes out.
